// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once


#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

namespace bitget_sbe
{
namespace detail
{
namespace schema
{
namespace types
{
struct padding6{};
struct tradeSide
{
    struct Buy{};
    struct Sell{};

};
struct padding4{};
struct messageHeader
{
struct blockLength{};
struct templateId{};
struct schemaId{};
struct version{};

};
struct blockLength_0{};
struct groupSize16Encoding
{
using blockLength = ::bitget_sbe::detail::schema::types::blockLength_0;
struct numInGroup{};

};
struct timestampType{};
struct padding1{};
struct varString8
{
struct length{};
struct varData{};

};
struct sequenceType{};
struct padding3{};
struct priceType{};
struct sizeType{};
struct symbolType{};
struct exponentType{};
struct padding7{};
struct padding5{};
struct padding0{};
struct padding2{};

} // namespace types
} //namespace schema
} // namespace detail
struct schema
{
struct types
{
using padding6 = ::bitget_sbe::detail::schema::types::padding6;
using tradeSide = ::bitget_sbe::detail::schema::types::tradeSide;
using padding4 = ::bitget_sbe::detail::schema::types::padding4;
using messageHeader = ::bitget_sbe::detail::schema::types::messageHeader;
using groupSize16Encoding = ::bitget_sbe::detail::schema::types::groupSize16Encoding;
using timestampType = ::bitget_sbe::detail::schema::types::timestampType;
using padding1 = ::bitget_sbe::detail::schema::types::padding1;
using varString8 = ::bitget_sbe::detail::schema::types::varString8;
using sequenceType = ::bitget_sbe::detail::schema::types::sequenceType;
using padding3 = ::bitget_sbe::detail::schema::types::padding3;
using priceType = ::bitget_sbe::detail::schema::types::priceType;
using sizeType = ::bitget_sbe::detail::schema::types::sizeType;
using symbolType = ::bitget_sbe::detail::schema::types::symbolType;
using exponentType = ::bitget_sbe::detail::schema::types::exponentType;
using padding7 = ::bitget_sbe::detail::schema::types::padding7;
using padding5 = ::bitget_sbe::detail::schema::types::padding5;
using padding0 = ::bitget_sbe::detail::schema::types::padding0;
using padding2 = ::bitget_sbe::detail::schema::types::padding2;

};
struct messages
{
struct Depth50
{
    struct ts{};
    struct seq{};
    struct priceExponent{};
    struct sizeExponent{};
    struct padding{};
struct asks
{
    struct price{};
    struct size{};

};
struct bids
{
    struct price{};
    struct size{};

};
    struct symbol{};

};

struct BestBidAsk
{
    struct ts{};
    struct bid1Price{};
    struct bid1Size{};
    struct ask1Price{};
    struct ask1Size{};
    struct priceExponent{};
    struct sizeExponent{};
    struct padding{};
    struct symbol{};

};

struct Trade
{
    struct priceExponent{};
    struct sizeExponent{};
    struct padding{};
struct trades
{
    struct ts{};
    struct execId{};
    struct price{};
    struct size{};
    struct side : ::bitget_sbe::detail::schema::types::tradeSide{};
    struct padding{};

};
    struct symbol{};

};


};
};


namespace types
{
template<typename Byte>
class messageHeader;
} // namespace types
} // namespace bitget_sbe

namespace sbepp
{

template<>
class schema_traits<::bitget_sbe::schema>
{
public:
    static constexpr const char* package() noexcept
    {
        return "com.upex.stream.sbe";
    }

    static constexpr schema_id_t id() noexcept
    {
        return 1;
    }

    static constexpr version_t version() noexcept
    {
        return 1;
    }

    static constexpr const char* semantic_version() noexcept
    {
        return "1.0.0";
    }

    static constexpr endian byte_order() noexcept
    {
        return ::sbepp::endian::little;
    }

    static constexpr const char* description() noexcept
    {
        return "UPEX Market Data SBE Schema";
    }

    
    template<typename Byte>
    using header_type = ::bitget_sbe::types::messageHeader<Byte>;
    using header_type_tag = ::bitget_sbe::schema::types::messageHeader;
    using type_tags = ::sbepp::type_list<::bitget_sbe::schema::types::padding6, ::bitget_sbe::schema::types::tradeSide, ::bitget_sbe::schema::types::padding4, ::bitget_sbe::schema::types::messageHeader, ::bitget_sbe::schema::types::groupSize16Encoding, ::bitget_sbe::schema::types::timestampType, ::bitget_sbe::schema::types::padding1, ::bitget_sbe::schema::types::varString8, ::bitget_sbe::schema::types::sequenceType, ::bitget_sbe::schema::types::padding3, ::bitget_sbe::schema::types::priceType, ::bitget_sbe::schema::types::sizeType, ::bitget_sbe::schema::types::symbolType, ::bitget_sbe::schema::types::exponentType, ::bitget_sbe::schema::types::padding7, ::bitget_sbe::schema::types::padding5, ::bitget_sbe::schema::types::padding0, ::bitget_sbe::schema::types::padding2>;
    using message_tags = ::sbepp::type_list<::bitget_sbe::schema::messages::Depth50, ::bitget_sbe::schema::messages::BestBidAsk, ::bitget_sbe::schema::messages::Trade>;
};

} // namespace sbepp

SBEPP_WARNINGS_ON();
