// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace gate_sbe
{


namespace types
{

enum class Event : ::std::int8_t
{
    Subscribe = 0,
    Unsubscribe = 1,
    Update = 2,
    All = 3,
    Api = 4
};

template<typename Visitor>
SBEPP_CPP14_CONSTEXPR void tag_invoke(
    ::sbepp::detail::visit_tag, Event e, Visitor& visitor) noexcept
{
    switch(e)
    {
    case Event::Subscribe:
        visitor.on_enum_value(e, ::gate_sbe::schema::types::Event::Subscribe{});
        break;
    case Event::Unsubscribe:
        visitor.on_enum_value(e, ::gate_sbe::schema::types::Event::Unsubscribe{});
        break;
    case Event::Update:
        visitor.on_enum_value(e, ::gate_sbe::schema::types::Event::Update{});
        break;
    case Event::All:
        visitor.on_enum_value(e, ::gate_sbe::schema::types::Event::All{});
        break;
    case Event::Api:
        visitor.on_enum_value(e, ::gate_sbe::schema::types::Event::Api{});
        break;
    default:
        visitor.on_enum_value(e, ::sbepp::unknown_enum_value_tag{});
    }
}


} // namespace types
} // namespace gate_sbe

namespace sbepp
{

template<>
class enum_traits<::gate_sbe::schema::types::Event>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Event";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    using encoding_type = ::std::int8_t;
    using encoding_type_tag = ::sbepp::int8_opt_t;
    
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::gate_sbe::types::Event;
    using value_tags = ::sbepp::type_list<::gate_sbe::schema::types::Event::Subscribe, ::gate_sbe::schema::types::Event::Unsubscribe, ::gate_sbe::schema::types::Event::Update, ::gate_sbe::schema::types::Event::All, ::gate_sbe::schema::types::Event::Api>;
};

template<>
struct traits_tag<::gate_sbe::types::Event>
{
    using type = ::gate_sbe::schema::types::Event;
};


template<>
class enum_value_traits<::gate_sbe::schema::types::Event::Subscribe>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Subscribe";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::gate_sbe::types::Event value() noexcept
    {
        return ::gate_sbe::types::Event::Subscribe;
    }
};

template<>
class enum_value_traits<::gate_sbe::schema::types::Event::Unsubscribe>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Unsubscribe";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::gate_sbe::types::Event value() noexcept
    {
        return ::gate_sbe::types::Event::Unsubscribe;
    }
};

template<>
class enum_value_traits<::gate_sbe::schema::types::Event::Update>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Update";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::gate_sbe::types::Event value() noexcept
    {
        return ::gate_sbe::types::Event::Update;
    }
};

template<>
class enum_value_traits<::gate_sbe::schema::types::Event::All>
{
public:
    static constexpr const char* name() noexcept
    {
        return "All";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::gate_sbe::types::Event value() noexcept
    {
        return ::gate_sbe::types::Event::All;
    }
};

template<>
class enum_value_traits<::gate_sbe::schema::types::Event::Api>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Api";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::gate_sbe::types::Event value() noexcept
    {
        return ::gate_sbe::types::Event::Api;
    }
};

} // namespace sbepp

SBEPP_WARNINGS_ON();
