// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace gate_sbe
{


namespace types
{

enum class PosMarginMode : ::std::int8_t
{
    Isolated = 0,
    Cross = 1
};

template<typename Visitor>
SBEPP_CPP14_CONSTEXPR void tag_invoke(
    ::sbepp::detail::visit_tag, PosMarginMode e, Visitor& visitor) noexcept
{
    switch(e)
    {
    case PosMarginMode::Isolated:
        visitor.on_enum_value(e, ::gate_sbe::schema::types::PosMarginMode::Isolated{});
        break;
    case PosMarginMode::Cross:
        visitor.on_enum_value(e, ::gate_sbe::schema::types::PosMarginMode::Cross{});
        break;
    default:
        visitor.on_enum_value(e, ::sbepp::unknown_enum_value_tag{});
    }
}


} // namespace types
} // namespace gate_sbe

namespace sbepp
{

template<>
class enum_traits<::gate_sbe::schema::types::PosMarginMode>
{
public:
    static constexpr const char* name() noexcept
    {
        return "PosMarginMode";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    using encoding_type = ::std::int8_t;
    using encoding_type_tag = ::sbepp::int8_opt_t;
    
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::gate_sbe::types::PosMarginMode;
    using value_tags = ::sbepp::type_list<::gate_sbe::schema::types::PosMarginMode::Isolated, ::gate_sbe::schema::types::PosMarginMode::Cross>;
};

template<>
struct traits_tag<::gate_sbe::types::PosMarginMode>
{
    using type = ::gate_sbe::schema::types::PosMarginMode;
};


template<>
class enum_value_traits<::gate_sbe::schema::types::PosMarginMode::Isolated>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Isolated";
    }

    static constexpr const char* description() noexcept
    {
        return "isolated";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::gate_sbe::types::PosMarginMode value() noexcept
    {
        return ::gate_sbe::types::PosMarginMode::Isolated;
    }
};

template<>
class enum_value_traits<::gate_sbe::schema::types::PosMarginMode::Cross>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Cross";
    }

    static constexpr const char* description() noexcept
    {
        return "cross";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::gate_sbe::types::PosMarginMode value() noexcept
    {
        return ::gate_sbe::types::PosMarginMode::Cross;
    }
};

} // namespace sbepp

SBEPP_WARNINGS_ON();
