// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace gate_sbe
{


namespace types
{

enum class Role : ::std::int8_t
{
    Maker = 0,
    Taker = 1
};

template<typename Visitor>
SBEPP_CPP14_CONSTEXPR void tag_invoke(
    ::sbepp::detail::visit_tag, Role e, Visitor& visitor) noexcept
{
    switch(e)
    {
    case Role::Maker:
        visitor.on_enum_value(e, ::gate_sbe::schema::types::Role::Maker{});
        break;
    case Role::Taker:
        visitor.on_enum_value(e, ::gate_sbe::schema::types::Role::Taker{});
        break;
    default:
        visitor.on_enum_value(e, ::sbepp::unknown_enum_value_tag{});
    }
}


} // namespace types
} // namespace gate_sbe

namespace sbepp
{

template<>
class enum_traits<::gate_sbe::schema::types::Role>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Role";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    using encoding_type = ::std::int8_t;
    using encoding_type_tag = ::sbepp::int8_opt_t;
    
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::gate_sbe::types::Role;
    using value_tags = ::sbepp::type_list<::gate_sbe::schema::types::Role::Maker, ::gate_sbe::schema::types::Role::Taker>;
};

template<>
struct traits_tag<::gate_sbe::types::Role>
{
    using type = ::gate_sbe::schema::types::Role;
};


template<>
class enum_value_traits<::gate_sbe::schema::types::Role::Maker>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Maker";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::gate_sbe::types::Role value() noexcept
    {
        return ::gate_sbe::types::Role::Maker;
    }
};

template<>
class enum_value_traits<::gate_sbe::schema::types::Role::Taker>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Taker";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::gate_sbe::types::Role value() noexcept
    {
        return ::gate_sbe::types::Role::Taker;
    }
};

} // namespace sbepp

SBEPP_WARNINGS_ON();
