// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include "schema/schema.hpp"
#include "types/padding6.hpp"
#include "types/tradeSide.hpp"
#include "types/padding4.hpp"
#include "types/messageHeader.hpp"
#include "types/groupSize16Encoding.hpp"
#include "types/timestampType.hpp"
#include "types/padding1.hpp"
#include "types/varString8.hpp"
#include "types/sequenceType.hpp"
#include "types/padding3.hpp"
#include "types/priceType.hpp"
#include "types/sizeType.hpp"
#include "types/symbolType.hpp"
#include "types/exponentType.hpp"
#include "types/padding7.hpp"
#include "types/padding5.hpp"
#include "types/padding0.hpp"
#include "types/padding2.hpp"
#include "messages/Depth50.hpp"
#include "messages/BestBidAsk.hpp"
#include "messages/Trade.hpp"
