// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bitget_sbe
{
namespace detail
{
namespace types
{

class blockLength_0
    : public ::sbepp::detail::required_base<::std::uint16_t, blockLength_0>
{
public:
    using ::sbepp::detail::required_base<
        ::std::uint16_t, blockLength_0>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {65534};
    }
};

class numInGroup
    : public ::sbepp::detail::required_base<::std::uint16_t, numInGroup>
{
public:
    using ::sbepp::detail::required_base<
        ::std::uint16_t, numInGroup>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {65534};
    }
};

} // namespace types
} // namespace detail

namespace types
{

template<typename Byte>
class groupSize16Encoding : public ::sbepp::detail::composite_base<Byte>
{
public:
    using ::sbepp::detail::composite_base<Byte>::composite_base;
    using ::sbepp::detail::composite_base<Byte>::operator();

    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::detail::types::blockLength_0 blockLength() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::detail::types::blockLength_0, ::bitget_sbe::detail::types::blockLength_0::value_type, ::sbepp::endian::little>(*this, 0);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void blockLength(::bitget_sbe::detail::types::blockLength_0 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 0, v.value());
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::types::groupSize16Encoding::blockLength,
        Args&&... args) const noexcept
        -> decltype(blockLength(std::forward<Args>(args)...))
    {
        return blockLength(std::forward<Args>(args)...);
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::detail::types::numInGroup numInGroup() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::detail::types::numInGroup, ::bitget_sbe::detail::types::numInGroup::value_type, ::sbepp::endian::little>(*this, 2);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void numInGroup(::bitget_sbe::detail::types::numInGroup v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 2, v.value());
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::types::groupSize16Encoding::numInGroup,
        Args&&... args) const noexcept
        -> decltype(numInGroup(std::forward<Args>(args)...))
    {
        return numInGroup(std::forward<Args>(args)...);
    }


    constexpr std::size_t
        operator()(::sbepp::detail::size_bytes_tag) const noexcept
    {
        return 4;
    }

    template<typename Visitor>
    constexpr bool operator()(
        ::sbepp::detail::visit_tag, Visitor& v) const
    {
        return v.on_composite(*this, ::bitget_sbe::schema::types::groupSize16Encoding{});
    }


    template<typename Visitor>
    constexpr bool operator()(
        ::sbepp::detail::visit_children_tag, Visitor& v) const
    {
        return v.on_type(this->blockLength(), ::bitget_sbe::schema::types::groupSize16Encoding::blockLength{})
||v.on_type(this->numInGroup(), ::bitget_sbe::schema::types::groupSize16Encoding::numInGroup{});
    }

};

} // namespace types
} // namespace bitget_sbe

namespace sbepp
{

template<>
class type_traits<::bitget_sbe::schema::types::groupSize16Encoding::blockLength>
{
public:
    static constexpr const char* name() noexcept
    {
        return "blockLength";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint16_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {0};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bitget_sbe::detail::types::blockLength_0;
};

template<>
struct traits_tag<::bitget_sbe::detail::types::blockLength_0>
{
    using type = ::bitget_sbe::schema::types::groupSize16Encoding::blockLength;
};


template<>
class type_traits<::bitget_sbe::schema::types::groupSize16Encoding::numInGroup>
{
public:
    static constexpr const char* name() noexcept
    {
        return "numInGroup";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint16_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {2};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bitget_sbe::detail::types::numInGroup;
};

template<>
struct traits_tag<::bitget_sbe::detail::types::numInGroup>
{
    using type = ::bitget_sbe::schema::types::groupSize16Encoding::numInGroup;
};


template<>
class composite_traits<::bitget_sbe::schema::types::groupSize16Encoding>
{
public:
    static constexpr const char* name() noexcept
    {
        return "groupSize16Encoding";
    }

    static constexpr const char* description() noexcept
    {
        return "Group size encoding";
    }

    

    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::bitget_sbe::types::groupSize16Encoding<Byte>;

    static constexpr std::size_t size_bytes() noexcept
    {
        return 4;
    }

    using element_tags = ::sbepp::type_list<::bitget_sbe::schema::types::groupSize16Encoding::blockLength, ::bitget_sbe::schema::types::groupSize16Encoding::numInGroup>;
};

template<typename Byte>
struct traits_tag<::bitget_sbe::types::groupSize16Encoding<Byte>>
{
    using type = ::bitget_sbe::schema::types::groupSize16Encoding;
};


} // namespace sbepp

SBEPP_WARNINGS_ON();
