// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bitget_sbe
{
namespace detail
{
namespace types
{

class blockLength
    : public ::sbepp::detail::required_base<::std::uint16_t, blockLength>
{
public:
    using ::sbepp::detail::required_base<
        ::std::uint16_t, blockLength>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {65534};
    }
};

class templateId
    : public ::sbepp::detail::required_base<::std::uint16_t, templateId>
{
public:
    using ::sbepp::detail::required_base<
        ::std::uint16_t, templateId>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {65534};
    }
};

class schemaId
    : public ::sbepp::detail::required_base<::std::uint16_t, schemaId>
{
public:
    using ::sbepp::detail::required_base<
        ::std::uint16_t, schemaId>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {65534};
    }
};

class version
    : public ::sbepp::detail::required_base<::std::uint16_t, version>
{
public:
    using ::sbepp::detail::required_base<
        ::std::uint16_t, version>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {65534};
    }
};

} // namespace types
} // namespace detail

namespace types
{

template<typename Byte>
class messageHeader : public ::sbepp::detail::composite_base<Byte>
{
public:
    using ::sbepp::detail::composite_base<Byte>::composite_base;
    using ::sbepp::detail::composite_base<Byte>::operator();

    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::detail::types::blockLength blockLength() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::detail::types::blockLength, ::bitget_sbe::detail::types::blockLength::value_type, ::sbepp::endian::little>(*this, 0);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void blockLength(::bitget_sbe::detail::types::blockLength v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 0, v.value());
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::types::messageHeader::blockLength,
        Args&&... args) const noexcept
        -> decltype(blockLength(std::forward<Args>(args)...))
    {
        return blockLength(std::forward<Args>(args)...);
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::detail::types::templateId templateId() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::detail::types::templateId, ::bitget_sbe::detail::types::templateId::value_type, ::sbepp::endian::little>(*this, 2);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void templateId(::bitget_sbe::detail::types::templateId v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 2, v.value());
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::types::messageHeader::templateId,
        Args&&... args) const noexcept
        -> decltype(templateId(std::forward<Args>(args)...))
    {
        return templateId(std::forward<Args>(args)...);
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::detail::types::schemaId schemaId() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::detail::types::schemaId, ::bitget_sbe::detail::types::schemaId::value_type, ::sbepp::endian::little>(*this, 4);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void schemaId(::bitget_sbe::detail::types::schemaId v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 4, v.value());
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::types::messageHeader::schemaId,
        Args&&... args) const noexcept
        -> decltype(schemaId(std::forward<Args>(args)...))
    {
        return schemaId(std::forward<Args>(args)...);
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::detail::types::version version() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::detail::types::version, ::bitget_sbe::detail::types::version::value_type, ::sbepp::endian::little>(*this, 6);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void version(::bitget_sbe::detail::types::version v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 6, v.value());
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::types::messageHeader::version,
        Args&&... args) const noexcept
        -> decltype(version(std::forward<Args>(args)...))
    {
        return version(std::forward<Args>(args)...);
    }


    constexpr std::size_t
        operator()(::sbepp::detail::size_bytes_tag) const noexcept
    {
        return 8;
    }

    template<typename Visitor>
    constexpr bool operator()(
        ::sbepp::detail::visit_tag, Visitor& v) const
    {
        return v.on_composite(*this, ::bitget_sbe::schema::types::messageHeader{});
    }


    template<typename Visitor>
    constexpr bool operator()(
        ::sbepp::detail::visit_children_tag, Visitor& v) const
    {
        return v.on_type(this->blockLength(), ::bitget_sbe::schema::types::messageHeader::blockLength{})
||v.on_type(this->templateId(), ::bitget_sbe::schema::types::messageHeader::templateId{})
||v.on_type(this->schemaId(), ::bitget_sbe::schema::types::messageHeader::schemaId{})
||v.on_type(this->version(), ::bitget_sbe::schema::types::messageHeader::version{});
    }

};

} // namespace types
} // namespace bitget_sbe

namespace sbepp
{

template<>
class type_traits<::bitget_sbe::schema::types::messageHeader::blockLength>
{
public:
    static constexpr const char* name() noexcept
    {
        return "blockLength";
    }

    static constexpr const char* description() noexcept
    {
        return "Root block length";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint16_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {0};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bitget_sbe::detail::types::blockLength;
};

template<>
struct traits_tag<::bitget_sbe::detail::types::blockLength>
{
    using type = ::bitget_sbe::schema::types::messageHeader::blockLength;
};


template<>
class type_traits<::bitget_sbe::schema::types::messageHeader::templateId>
{
public:
    static constexpr const char* name() noexcept
    {
        return "templateId";
    }

    static constexpr const char* description() noexcept
    {
        return "Template ID";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint16_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {2};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bitget_sbe::detail::types::templateId;
};

template<>
struct traits_tag<::bitget_sbe::detail::types::templateId>
{
    using type = ::bitget_sbe::schema::types::messageHeader::templateId;
};


template<>
class type_traits<::bitget_sbe::schema::types::messageHeader::schemaId>
{
public:
    static constexpr const char* name() noexcept
    {
        return "schemaId";
    }

    static constexpr const char* description() noexcept
    {
        return "Schema ID";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint16_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {4};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bitget_sbe::detail::types::schemaId;
};

template<>
struct traits_tag<::bitget_sbe::detail::types::schemaId>
{
    using type = ::bitget_sbe::schema::types::messageHeader::schemaId;
};


template<>
class type_traits<::bitget_sbe::schema::types::messageHeader::version>
{
public:
    static constexpr const char* name() noexcept
    {
        return "version";
    }

    static constexpr const char* description() noexcept
    {
        return "Schema version";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint16_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {6};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bitget_sbe::detail::types::version;
};

template<>
struct traits_tag<::bitget_sbe::detail::types::version>
{
    using type = ::bitget_sbe::schema::types::messageHeader::version;
};


template<>
class composite_traits<::bitget_sbe::schema::types::messageHeader>
{
public:
    static constexpr const char* name() noexcept
    {
        return "messageHeader";
    }

    static constexpr const char* description() noexcept
    {
        return "Standard SBE Message Header";
    }

    

    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::bitget_sbe::types::messageHeader<Byte>;

    static constexpr std::size_t size_bytes() noexcept
    {
        return 8;
    }

    using element_tags = ::sbepp::type_list<::bitget_sbe::schema::types::messageHeader::blockLength, ::bitget_sbe::schema::types::messageHeader::templateId, ::bitget_sbe::schema::types::messageHeader::schemaId, ::bitget_sbe::schema::types::messageHeader::version>;
};

template<typename Byte>
struct traits_tag<::bitget_sbe::types::messageHeader<Byte>>
{
    using type = ::bitget_sbe::schema::types::messageHeader;
};


} // namespace sbepp

SBEPP_WARNINGS_ON();
