// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bitget_sbe
{


namespace types
{

template<typename Byte>
using padding5 = ::sbepp::detail::static_array_ref<
    Byte, ::std::uint8_t, 5, ::bitget_sbe::schema::types::padding5>;

} // namespace types
} // namespace bitget_sbe

namespace sbepp
{

template<>
class type_traits<::bitget_sbe::schema::types::padding5>
{
public:
    static constexpr const char* name() noexcept
    {
        return "padding5";
    }

    static constexpr const char* description() noexcept
    {
        return "5 bytes padding for alignment";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint8_t;
    
    
    static constexpr length_t length() noexcept
    {
        return 5;
    }
    
    
    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    
    template<typename Byte>
    using value_type = ::bitget_sbe::types::padding5<Byte>;
};



} // namespace sbepp

SBEPP_WARNINGS_ON();
