// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bitget_sbe
{


namespace types
{

class priceType
    : public ::sbepp::detail::required_base<::std::int64_t, priceType>
{
public:
    using ::sbepp::detail::required_base<
        ::std::int64_t, priceType>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {-9223372036854775807};
    }

    static constexpr value_type max_value() noexcept
    {
        return {9223372036854775807};
    }
};

} // namespace types
} // namespace bitget_sbe

namespace sbepp
{

template<>
class type_traits<::bitget_sbe::schema::types::priceType>
{
public:
    static constexpr const char* name() noexcept
    {
        return "priceType";
    }

    static constexpr const char* description() noexcept
    {
        return "Price mantissa";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::int64_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    
    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bitget_sbe::types::priceType;
};

template<>
struct traits_tag<::bitget_sbe::types::priceType>
{
    using type = ::bitget_sbe::schema::types::priceType;
};


} // namespace sbepp

SBEPP_WARNINGS_ON();
