// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bitget_sbe
{


namespace types
{

enum class tradeSide : ::std::uint8_t
{
    Buy = 0,
    Sell = 1
};

template<typename Visitor>
SBEPP_CPP14_CONSTEXPR void tag_invoke(
    ::sbepp::detail::visit_tag, tradeSide e, Visitor& visitor) noexcept
{
    switch(e)
    {
    case tradeSide::Buy:
        visitor.on_enum_value(e, ::bitget_sbe::schema::types::tradeSide::Buy{});
        break;
    case tradeSide::Sell:
        visitor.on_enum_value(e, ::bitget_sbe::schema::types::tradeSide::Sell{});
        break;
    default:
        visitor.on_enum_value(e, ::sbepp::unknown_enum_value_tag{});
    }
}


} // namespace types
} // namespace bitget_sbe

namespace sbepp
{

template<>
class enum_traits<::bitget_sbe::schema::types::tradeSide>
{
public:
    static constexpr const char* name() noexcept
    {
        return "tradeSide";
    }

    static constexpr const char* description() noexcept
    {
        return "Trade side";
    }

    using encoding_type = ::std::uint8_t;
    using encoding_type_tag = ::sbepp::uint8_opt_t;
    
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::tradeSide;
    using value_tags = ::sbepp::type_list<::bitget_sbe::schema::types::tradeSide::Buy, ::bitget_sbe::schema::types::tradeSide::Sell>;
};

template<>
struct traits_tag<::bitget_sbe::types::tradeSide>
{
    using type = ::bitget_sbe::schema::types::tradeSide;
};


template<>
class enum_value_traits<::bitget_sbe::schema::types::tradeSide::Buy>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Buy";
    }

    static constexpr const char* description() noexcept
    {
        return "Buy side";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bitget_sbe::types::tradeSide value() noexcept
    {
        return ::bitget_sbe::types::tradeSide::Buy;
    }
};

template<>
class enum_value_traits<::bitget_sbe::schema::types::tradeSide::Sell>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Sell";
    }

    static constexpr const char* description() noexcept
    {
        return "Sell side";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bitget_sbe::types::tradeSide value() noexcept
    {
        return ::bitget_sbe::types::tradeSide::Sell;
    }
};

} // namespace sbepp

SBEPP_WARNINGS_ON();
