// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"
#include "../types/messageHeader.hpp"
#include "../types/varString8.hpp"
#include "../types/padding6.hpp"
#include "../types/exponentType.hpp"
#include "../types/sizeType.hpp"
#include "../types/priceType.hpp"
#include "../types/timestampType.hpp"


namespace bitget_sbe
{


namespace messages
{

template<typename Byte>
class BestBidAsk : public ::sbepp::detail::message_base<
    Byte, ::bitget_sbe::types::messageHeader<Byte>>
{
public:
    using ::sbepp::detail::message_base<
        Byte, ::bitget_sbe::types::messageHeader<Byte>>::message_base;
    using ::sbepp::detail::message_base<
        Byte, ::bitget_sbe::types::messageHeader<Byte>>::operator();

    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::timestampType ts() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::timestampType, ::bitget_sbe::types::timestampType::value_type, ::sbepp::endian::little>(*this, 8);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void ts(::bitget_sbe::types::timestampType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 8, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::priceType bid1Price() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::priceType, ::bitget_sbe::types::priceType::value_type, ::sbepp::endian::little>(*this, 16);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void bid1Price(::bitget_sbe::types::priceType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 16, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::sizeType bid1Size() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::sizeType, ::bitget_sbe::types::sizeType::value_type, ::sbepp::endian::little>(*this, 24);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void bid1Size(::bitget_sbe::types::sizeType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 24, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::priceType ask1Price() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::priceType, ::bitget_sbe::types::priceType::value_type, ::sbepp::endian::little>(*this, 32);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void ask1Price(::bitget_sbe::types::priceType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 32, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::sizeType ask1Size() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::sizeType, ::bitget_sbe::types::sizeType::value_type, ::sbepp::endian::little>(*this, 40);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void ask1Size(::bitget_sbe::types::sizeType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 40, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::exponentType priceExponent() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::exponentType, ::bitget_sbe::types::exponentType::value_type, ::sbepp::endian::little>(*this, 48);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void priceExponent(::bitget_sbe::types::exponentType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 48, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::exponentType sizeExponent() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::exponentType, ::bitget_sbe::types::exponentType::value_type, ::sbepp::endian::little>(*this, 49);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void sizeExponent(::bitget_sbe::types::exponentType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 49, v.value());
    }
    constexpr ::bitget_sbe::types::padding6<Byte> padding() const noexcept
    {
        return ::sbepp::detail::get_static_field_view<::bitget_sbe::types::padding6<Byte>>(
            *this, 50);
    }

    constexpr ::sbepp::detail::dynamic_array_ref<
    Byte, ::std::uint8_t, ::bitget_sbe::detail::types::length, ::sbepp::endian::little> symbol() const noexcept
    {
        return ::sbepp::detail::get_first_dynamic_field_view<::sbepp::detail::dynamic_array_ref<
    Byte, ::std::uint8_t, ::bitget_sbe::detail::types::length, ::sbepp::endian::little>>(
            *this);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        ts(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::timestampType>
    {
        return c.template get_value<::bitget_sbe::types::timestampType, ::std::uint64_t, ::sbepp::endian::little>(
            *this, 0, 8);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void ts(
        ::bitget_sbe::types::timestampType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 8, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        bid1Price(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::priceType>
    {
        return c.template get_value<::bitget_sbe::types::priceType, ::std::int64_t, ::sbepp::endian::little>(
            *this, 0, 16);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void bid1Price(
        ::bitget_sbe::types::priceType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 16, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        bid1Size(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::sizeType>
    {
        return c.template get_value<::bitget_sbe::types::sizeType, ::std::int64_t, ::sbepp::endian::little>(
            *this, 0, 24);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void bid1Size(
        ::bitget_sbe::types::sizeType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 24, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        ask1Price(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::priceType>
    {
        return c.template get_value<::bitget_sbe::types::priceType, ::std::int64_t, ::sbepp::endian::little>(
            *this, 0, 32);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void ask1Price(
        ::bitget_sbe::types::priceType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 32, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        ask1Size(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::sizeType>
    {
        return c.template get_value<::bitget_sbe::types::sizeType, ::std::int64_t, ::sbepp::endian::little>(
            *this, 0, 40);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void ask1Size(
        ::bitget_sbe::types::sizeType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 40, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        priceExponent(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::exponentType>
    {
        return c.template get_value<::bitget_sbe::types::exponentType, ::std::int8_t, ::sbepp::endian::little>(
            *this, 0, 48);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void priceExponent(
        ::bitget_sbe::types::exponentType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 48, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        sizeExponent(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::exponentType>
    {
        return c.template get_value<::bitget_sbe::types::exponentType, ::std::int8_t, ::sbepp::endian::little>(
            *this, 0, 49);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void sizeExponent(
        ::bitget_sbe::types::exponentType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 49, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto padding(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor,
            ::bitget_sbe::types::padding6<::sbepp::detail::cursor_byte_type_t<Cursor>>>
    {
        return c.template get_last_static_field_view<::bitget_sbe::types::padding6<::sbepp::detail::cursor_byte_type_t<Cursor>>>(
            *this, 0, 50);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    constexpr auto symbol(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor,
            ::sbepp::detail::dynamic_array_ref<
                ::sbepp::detail::cursor_byte_type_t<Cursor>,
                    ::std::uint8_t, ::bitget_sbe::detail::types::length, ::sbepp::endian::little>>
    {
        return c.template get_first_data_view<
            ::sbepp::detail::dynamic_array_ref<
                ::sbepp::detail::cursor_byte_type_t<Cursor>,
                    ::std::uint8_t, ::bitget_sbe::detail::types::length, ::sbepp::endian::little>>(
                        *this);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::BestBidAsk::ts,
        Args&&... args) const noexcept
        -> decltype(ts(std::forward<Args>(args)...))
    {
        return ts(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::BestBidAsk::bid1Price,
        Args&&... args) const noexcept
        -> decltype(bid1Price(std::forward<Args>(args)...))
    {
        return bid1Price(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::BestBidAsk::bid1Size,
        Args&&... args) const noexcept
        -> decltype(bid1Size(std::forward<Args>(args)...))
    {
        return bid1Size(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::BestBidAsk::ask1Price,
        Args&&... args) const noexcept
        -> decltype(ask1Price(std::forward<Args>(args)...))
    {
        return ask1Price(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::BestBidAsk::ask1Size,
        Args&&... args) const noexcept
        -> decltype(ask1Size(std::forward<Args>(args)...))
    {
        return ask1Size(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::BestBidAsk::priceExponent,
        Args&&... args) const noexcept
        -> decltype(priceExponent(std::forward<Args>(args)...))
    {
        return priceExponent(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::BestBidAsk::sizeExponent,
        Args&&... args) const noexcept
        -> decltype(sizeExponent(std::forward<Args>(args)...))
    {
        return sizeExponent(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::BestBidAsk::padding,
        Args&&... args) const noexcept
        -> decltype(padding(std::forward<Args>(args)...))
    {
        return padding(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::BestBidAsk::symbol,
        Args&&... args) const noexcept
        -> decltype(symbol(std::forward<Args>(args)...))
    {
        return symbol(std::forward<Args>(args)...);
    }


    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP14_CONSTEXPR ::bitget_sbe::types::messageHeader<Byte>
        operator()(::sbepp::detail::fill_message_header_tag) const noexcept
    {
        auto header = operator()(::sbepp::detail::get_header_tag{});
        header.schemaId({1});
        header.templateId({1002});
        header.version({1});
        header.blockLength({48});
        
        
        return header;
    }


    SBEPP_CPP20_CONSTEXPR std::size_t operator()(
        ::sbepp::detail::size_bytes_tag) const noexcept
    {
        const auto last = symbol();
        return ::sbepp::addressof(last) + ::sbepp::size_bytes(last)
               - (*this)(::sbepp::detail::addressof_tag{});
    }


    template<typename Visitor, typename Cursor>
    SBEPP_CPP14_CONSTEXPR void operator()(
        ::sbepp::detail::visit_tag, Visitor& v, Cursor& c)
    {
        v.on_message(*this, c, ::bitget_sbe::schema::messages::BestBidAsk{});
    }


    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_children_tag, Visitor& v, Cursor& c) const
    {
        return v.on_field(this->ts(c), ::bitget_sbe::schema::messages::BestBidAsk::ts{})
||v.on_field(this->bid1Price(c), ::bitget_sbe::schema::messages::BestBidAsk::bid1Price{})
||v.on_field(this->bid1Size(c), ::bitget_sbe::schema::messages::BestBidAsk::bid1Size{})
||v.on_field(this->ask1Price(c), ::bitget_sbe::schema::messages::BestBidAsk::ask1Price{})
||v.on_field(this->ask1Size(c), ::bitget_sbe::schema::messages::BestBidAsk::ask1Size{})
||v.on_field(this->priceExponent(c), ::bitget_sbe::schema::messages::BestBidAsk::priceExponent{})
||v.on_field(this->sizeExponent(c), ::bitget_sbe::schema::messages::BestBidAsk::sizeExponent{})
||v.on_field(this->padding(c), ::bitget_sbe::schema::messages::BestBidAsk::padding{})
||v.on_data(this->symbol(c), ::bitget_sbe::schema::messages::BestBidAsk::symbol{});
    }

};

} // namespace messages
} // namespace bitget_sbe

namespace sbepp
{

template<>
class field_traits<::bitget_sbe::schema::messages::BestBidAsk::ts>
{
public:
    static constexpr const char* name() noexcept
    {
        return "ts";
    }

    static constexpr member_id_t id() noexcept
    {
        return 1;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {0};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::timestampType;
    using value_type_tag = ::bitget_sbe::schema::types::timestampType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::BestBidAsk::bid1Price>
{
public:
    static constexpr const char* name() noexcept
    {
        return "bid1Price";
    }

    static constexpr member_id_t id() noexcept
    {
        return 2;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {8};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::priceType;
    using value_type_tag = ::bitget_sbe::schema::types::priceType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::BestBidAsk::bid1Size>
{
public:
    static constexpr const char* name() noexcept
    {
        return "bid1Size";
    }

    static constexpr member_id_t id() noexcept
    {
        return 3;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {16};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::sizeType;
    using value_type_tag = ::bitget_sbe::schema::types::sizeType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::BestBidAsk::ask1Price>
{
public:
    static constexpr const char* name() noexcept
    {
        return "ask1Price";
    }

    static constexpr member_id_t id() noexcept
    {
        return 4;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {24};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::priceType;
    using value_type_tag = ::bitget_sbe::schema::types::priceType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::BestBidAsk::ask1Size>
{
public:
    static constexpr const char* name() noexcept
    {
        return "ask1Size";
    }

    static constexpr member_id_t id() noexcept
    {
        return 5;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {32};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::sizeType;
    using value_type_tag = ::bitget_sbe::schema::types::sizeType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::BestBidAsk::priceExponent>
{
public:
    static constexpr const char* name() noexcept
    {
        return "priceExponent";
    }

    static constexpr member_id_t id() noexcept
    {
        return 6;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {40};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::exponentType;
    using value_type_tag = ::bitget_sbe::schema::types::exponentType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::BestBidAsk::sizeExponent>
{
public:
    static constexpr const char* name() noexcept
    {
        return "sizeExponent";
    }

    static constexpr member_id_t id() noexcept
    {
        return 7;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {41};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::exponentType;
    using value_type_tag = ::bitget_sbe::schema::types::exponentType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::BestBidAsk::padding>
{
public:
    static constexpr const char* name() noexcept
    {
        return "padding";
    }

    static constexpr member_id_t id() noexcept
    {
        return 100;
    }

    static constexpr const char* description() noexcept
    {
        return "Padding for 8-byte alignment";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {42};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::bitget_sbe::types::padding6<Byte>;
    using value_type_tag = ::bitget_sbe::schema::types::padding6;
};

template<>
class data_traits<::bitget_sbe::schema::messages::BestBidAsk::symbol>
{
public:
    static constexpr const char* name() noexcept
    {
        return "symbol";
    }

    static constexpr member_id_t id() noexcept
    {
        return 200;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    template<typename Byte>
    using value_type = ::sbepp::detail::dynamic_array_ref<
    Byte, ::std::uint8_t, ::bitget_sbe::detail::types::length, ::sbepp::endian::little>;

    using length_type = ::bitget_sbe::detail::types::length;
    using length_type_tag = ::bitget_sbe::schema::types::varString8::length;

    static constexpr ::std::size_t size_bytes(
        const length_type::value_type size) noexcept
    {
        return sizeof(size) + size;
    }
};

template<>
class message_traits<::bitget_sbe::schema::messages::BestBidAsk>
{
public:
    static constexpr const char* name() noexcept
    {
        return "BestBidAsk";
    }

    static constexpr const char* description() noexcept
    {
        return "Best bid and ask";
    }

    static constexpr message_id_t id() noexcept
    {
        return 1002;
    }

    static constexpr block_length_t block_length() noexcept
    {
        return 48;
    }

    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::bitget_sbe::messages::BestBidAsk<Byte>;
    using schema_tag = ::bitget_sbe::schema;
    static constexpr ::std::size_t size_bytes(
        const ::std::size_t total_data_size) noexcept
    {
        return ::sbepp::composite_traits<
            ::sbepp::schema_traits<schema_tag>::header_type_tag>::size_bytes()
            + block_length()
+ ::sbepp::data_traits<::bitget_sbe::schema::messages::BestBidAsk::symbol>::size_bytes(0)
+ total_data_size;
    }

    using field_tags = ::sbepp::type_list<::bitget_sbe::schema::messages::BestBidAsk::ts, ::bitget_sbe::schema::messages::BestBidAsk::bid1Price, ::bitget_sbe::schema::messages::BestBidAsk::bid1Size, ::bitget_sbe::schema::messages::BestBidAsk::ask1Price, ::bitget_sbe::schema::messages::BestBidAsk::ask1Size, ::bitget_sbe::schema::messages::BestBidAsk::priceExponent, ::bitget_sbe::schema::messages::BestBidAsk::sizeExponent, ::bitget_sbe::schema::messages::BestBidAsk::padding>;
    using group_tags = ::sbepp::type_list<>;
    using data_tags = ::sbepp::type_list<::bitget_sbe::schema::messages::BestBidAsk::symbol>;
};

template<typename Byte>
struct traits_tag<::bitget_sbe::messages::BestBidAsk<Byte>>
{
    using type = ::bitget_sbe::schema::messages::BestBidAsk;
};


} // namespace sbepp

SBEPP_WARNINGS_ON();
