// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"
#include "../types/messageHeader.hpp"
#include "../types/varString8.hpp"
#include "../types/padding6.hpp"
#include "../types/sequenceType.hpp"
#include "../types/timestampType.hpp"
#include "../types/exponentType.hpp"
#include "../types/groupSize16Encoding.hpp"
#include "../types/sizeType.hpp"
#include "../types/priceType.hpp"


namespace bitget_sbe
{
namespace detail
{
namespace messages
{




template<typename Byte>
class asks_entry : public ::sbepp::detail::entry_base<Byte, ::std::uint16_t>
{
public:
    using ::sbepp::detail::entry_base<Byte, ::std::uint16_t>::entry_base;
    using ::sbepp::detail::entry_base<Byte, ::std::uint16_t>::operator();

    
        SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::priceType price() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::priceType, ::bitget_sbe::types::priceType::value_type, ::sbepp::endian::little>(*this, 0);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void price(::bitget_sbe::types::priceType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 0, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::sizeType size() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::sizeType, ::bitget_sbe::types::sizeType::value_type, ::sbepp::endian::little>(*this, 8);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void size(::bitget_sbe::types::sizeType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 8, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        price(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::priceType>
    {
        return c.template get_value<::bitget_sbe::types::priceType, ::std::int64_t, ::sbepp::endian::little>(
            *this, 0, 0);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void price(
        ::bitget_sbe::types::priceType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 0, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto size(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::sizeType>
    {
        return c.template get_last_value<::bitget_sbe::types::sizeType, ::std::int64_t, ::sbepp::endian::little>(
            *this, 0, 8);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void size(::bitget_sbe::types::sizeType v, Cursor&& c) const noexcept
    {
        return c.template set_last_value<::sbepp::endian::little>(
            *this, 0, 8, v.value());
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::asks::price,
        Args&&... args) const noexcept
        -> decltype(price(std::forward<Args>(args)...))
    {
        return price(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::asks::size,
        Args&&... args) const noexcept
        -> decltype(size(std::forward<Args>(args)...))
    {
        return size(std::forward<Args>(args)...);
    }

    
    SBEPP_CPP20_CONSTEXPR std::size_t operator()(
        ::sbepp::detail::size_bytes_tag) const noexcept
    {
        return 0 + (*this)(::sbepp::detail::get_block_length_tag{});
    }


    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_tag, Visitor& v, Cursor& c) const
    {
        return v.on_entry(*this, c);
    }

    
    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_children_tag, Visitor& v, Cursor& c) const
    {
        return v.on_field(this->price(c), ::bitget_sbe::schema::messages::Depth50::asks::price{})
||v.on_field(this->size(c), ::bitget_sbe::schema::messages::Depth50::asks::size{});
    }

};


template<typename Byte>
class asks : public ::sbepp::detail::flat_group_base<
                  Byte,
                  ::bitget_sbe::detail::messages::asks_entry<Byte>,
                  ::bitget_sbe::types::groupSize16Encoding<Byte>>
{
public:
        using ::sbepp::detail::flat_group_base<
                Byte,
                ::bitget_sbe::detail::messages::asks_entry<Byte>,
                ::bitget_sbe::types::groupSize16Encoding<Byte>>::flat_group_base;
        using ::sbepp::detail::flat_group_base<
                Byte,
                ::bitget_sbe::detail::messages::asks_entry<Byte>,
                ::bitget_sbe::types::groupSize16Encoding<Byte>>::operator();
    
    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP14_CONSTEXPR ::bitget_sbe::types::groupSize16Encoding<Byte>
        operator()(
            ::sbepp::detail::fill_group_header_tag,
            ::bitget_sbe::detail::types::numInGroup num_in_group) const noexcept
    {
        auto header = operator()(::sbepp::detail::get_header_tag{});
        header.blockLength({16});
        header.numInGroup(num_in_group);
        
        
        return header;
    }


    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_tag, Visitor& v, Cursor& c) const
    {
        return v.on_group(*this, c, "asks");
    }
};




template<typename Byte>
class bids_entry : public ::sbepp::detail::entry_base<Byte, ::std::uint16_t>
{
public:
    using ::sbepp::detail::entry_base<Byte, ::std::uint16_t>::entry_base;
    using ::sbepp::detail::entry_base<Byte, ::std::uint16_t>::operator();

    
        SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::priceType price() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::priceType, ::bitget_sbe::types::priceType::value_type, ::sbepp::endian::little>(*this, 0);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void price(::bitget_sbe::types::priceType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 0, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::sizeType size() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::sizeType, ::bitget_sbe::types::sizeType::value_type, ::sbepp::endian::little>(*this, 8);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void size(::bitget_sbe::types::sizeType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 8, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        price(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::priceType>
    {
        return c.template get_value<::bitget_sbe::types::priceType, ::std::int64_t, ::sbepp::endian::little>(
            *this, 0, 0);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void price(
        ::bitget_sbe::types::priceType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 0, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto size(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::sizeType>
    {
        return c.template get_last_value<::bitget_sbe::types::sizeType, ::std::int64_t, ::sbepp::endian::little>(
            *this, 0, 8);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void size(::bitget_sbe::types::sizeType v, Cursor&& c) const noexcept
    {
        return c.template set_last_value<::sbepp::endian::little>(
            *this, 0, 8, v.value());
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::bids::price,
        Args&&... args) const noexcept
        -> decltype(price(std::forward<Args>(args)...))
    {
        return price(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::bids::size,
        Args&&... args) const noexcept
        -> decltype(size(std::forward<Args>(args)...))
    {
        return size(std::forward<Args>(args)...);
    }

    
    SBEPP_CPP20_CONSTEXPR std::size_t operator()(
        ::sbepp::detail::size_bytes_tag) const noexcept
    {
        return 0 + (*this)(::sbepp::detail::get_block_length_tag{});
    }


    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_tag, Visitor& v, Cursor& c) const
    {
        return v.on_entry(*this, c);
    }

    
    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_children_tag, Visitor& v, Cursor& c) const
    {
        return v.on_field(this->price(c), ::bitget_sbe::schema::messages::Depth50::bids::price{})
||v.on_field(this->size(c), ::bitget_sbe::schema::messages::Depth50::bids::size{});
    }

};


template<typename Byte>
class bids : public ::sbepp::detail::flat_group_base<
                  Byte,
                  ::bitget_sbe::detail::messages::bids_entry<Byte>,
                  ::bitget_sbe::types::groupSize16Encoding<Byte>>
{
public:
        using ::sbepp::detail::flat_group_base<
                Byte,
                ::bitget_sbe::detail::messages::bids_entry<Byte>,
                ::bitget_sbe::types::groupSize16Encoding<Byte>>::flat_group_base;
        using ::sbepp::detail::flat_group_base<
                Byte,
                ::bitget_sbe::detail::messages::bids_entry<Byte>,
                ::bitget_sbe::types::groupSize16Encoding<Byte>>::operator();
    
    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP14_CONSTEXPR ::bitget_sbe::types::groupSize16Encoding<Byte>
        operator()(
            ::sbepp::detail::fill_group_header_tag,
            ::bitget_sbe::detail::types::numInGroup num_in_group) const noexcept
    {
        auto header = operator()(::sbepp::detail::get_header_tag{});
        header.blockLength({16});
        header.numInGroup(num_in_group);
        
        
        return header;
    }


    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_tag, Visitor& v, Cursor& c) const
    {
        return v.on_group(*this, c, "bids");
    }
};

} // namespace messages
} // namespace detail

namespace messages
{

template<typename Byte>
class Depth50 : public ::sbepp::detail::message_base<
    Byte, ::bitget_sbe::types::messageHeader<Byte>>
{
public:
    using ::sbepp::detail::message_base<
        Byte, ::bitget_sbe::types::messageHeader<Byte>>::message_base;
    using ::sbepp::detail::message_base<
        Byte, ::bitget_sbe::types::messageHeader<Byte>>::operator();

    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::timestampType ts() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::timestampType, ::bitget_sbe::types::timestampType::value_type, ::sbepp::endian::little>(*this, 8);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void ts(::bitget_sbe::types::timestampType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 8, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::sequenceType seq() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::sequenceType, ::bitget_sbe::types::sequenceType::value_type, ::sbepp::endian::little>(*this, 16);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void seq(::bitget_sbe::types::sequenceType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 16, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::exponentType priceExponent() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::exponentType, ::bitget_sbe::types::exponentType::value_type, ::sbepp::endian::little>(*this, 24);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void priceExponent(::bitget_sbe::types::exponentType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 24, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bitget_sbe::types::exponentType sizeExponent() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bitget_sbe::types::exponentType, ::bitget_sbe::types::exponentType::value_type, ::sbepp::endian::little>(*this, 25);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void sizeExponent(::bitget_sbe::types::exponentType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 25, v.value());
    }
    constexpr ::bitget_sbe::types::padding6<Byte> padding() const noexcept
    {
        return ::sbepp::detail::get_static_field_view<::bitget_sbe::types::padding6<Byte>>(
            *this, 26);
    }

    constexpr ::bitget_sbe::detail::messages::asks<Byte> asks() const noexcept
    {
        return ::sbepp::detail::get_first_dynamic_field_view<::bitget_sbe::detail::messages::asks<Byte>>(
            *this);
    }

    constexpr ::bitget_sbe::detail::messages::bids<Byte> bids() const noexcept
    {
        return ::sbepp::detail::get_dynamic_field_view<::bitget_sbe::detail::messages::bids<Byte>>(*this, asks());
    }

    constexpr ::sbepp::detail::dynamic_array_ref<
    Byte, ::std::uint8_t, ::bitget_sbe::detail::types::length, ::sbepp::endian::little> symbol() const noexcept
    {
        return ::sbepp::detail::get_dynamic_field_view<::sbepp::detail::dynamic_array_ref<
    Byte, ::std::uint8_t, ::bitget_sbe::detail::types::length, ::sbepp::endian::little>>(
            *this, bids());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        ts(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::timestampType>
    {
        return c.template get_value<::bitget_sbe::types::timestampType, ::std::uint64_t, ::sbepp::endian::little>(
            *this, 0, 8);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void ts(
        ::bitget_sbe::types::timestampType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 8, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        seq(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::sequenceType>
    {
        return c.template get_value<::bitget_sbe::types::sequenceType, ::std::uint64_t, ::sbepp::endian::little>(
            *this, 0, 16);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void seq(
        ::bitget_sbe::types::sequenceType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 16, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        priceExponent(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::exponentType>
    {
        return c.template get_value<::bitget_sbe::types::exponentType, ::std::int8_t, ::sbepp::endian::little>(
            *this, 0, 24);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void priceExponent(
        ::bitget_sbe::types::exponentType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 24, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        sizeExponent(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::bitget_sbe::types::exponentType>
    {
        return c.template get_value<::bitget_sbe::types::exponentType, ::std::int8_t, ::sbepp::endian::little>(
            *this, 0, 25);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void sizeExponent(
        ::bitget_sbe::types::exponentType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 25, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto padding(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor,
            ::bitget_sbe::types::padding6<::sbepp::detail::cursor_byte_type_t<Cursor>>>
    {
        return c.template get_last_static_field_view<::bitget_sbe::types::padding6<::sbepp::detail::cursor_byte_type_t<Cursor>>>(
            *this, 0, 26);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    constexpr auto asks(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor,
            ::bitget_sbe::detail::messages::asks<::sbepp::detail::cursor_byte_type_t<Cursor>>>
    {
        return c.template get_first_group_view<
            ::bitget_sbe::detail::messages::asks<::sbepp::detail::cursor_byte_type_t<Cursor>>>(*this);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    constexpr auto bids(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor,
            ::bitget_sbe::detail::messages::bids<::sbepp::detail::cursor_byte_type_t<Cursor>>>
    {
        return c.template get_group_view<
            ::bitget_sbe::detail::messages::bids<::sbepp::detail::cursor_byte_type_t<Cursor>>>(
                *this, [this](){return this->bids();});
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    constexpr auto symbol(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor,
            ::sbepp::detail::dynamic_array_ref<
                ::sbepp::detail::cursor_byte_type_t<Cursor>,
                    ::std::uint8_t, ::bitget_sbe::detail::types::length, ::sbepp::endian::little>>
    {
        return c.template get_data_view<
            ::sbepp::detail::dynamic_array_ref<
                ::sbepp::detail::cursor_byte_type_t<Cursor>, ::std::uint8_t,
                    ::bitget_sbe::detail::types::length, ::sbepp::endian::little>>(
                        *this, [this](){return this->symbol();});
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::ts,
        Args&&... args) const noexcept
        -> decltype(ts(std::forward<Args>(args)...))
    {
        return ts(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::seq,
        Args&&... args) const noexcept
        -> decltype(seq(std::forward<Args>(args)...))
    {
        return seq(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::priceExponent,
        Args&&... args) const noexcept
        -> decltype(priceExponent(std::forward<Args>(args)...))
    {
        return priceExponent(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::sizeExponent,
        Args&&... args) const noexcept
        -> decltype(sizeExponent(std::forward<Args>(args)...))
    {
        return sizeExponent(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::padding,
        Args&&... args) const noexcept
        -> decltype(padding(std::forward<Args>(args)...))
    {
        return padding(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::asks,
        Args&&... args) const noexcept
        -> decltype(asks(std::forward<Args>(args)...))
    {
        return asks(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::bids,
        Args&&... args) const noexcept
        -> decltype(bids(std::forward<Args>(args)...))
    {
        return bids(std::forward<Args>(args)...);
    }
    template<typename... Args>
    SBEPP_CPP20_CONSTEXPR auto operator()(
        ::sbepp::detail::access_by_tag_tag,
        ::bitget_sbe::schema::messages::Depth50::symbol,
        Args&&... args) const noexcept
        -> decltype(symbol(std::forward<Args>(args)...))
    {
        return symbol(std::forward<Args>(args)...);
    }


    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP14_CONSTEXPR ::bitget_sbe::types::messageHeader<Byte>
        operator()(::sbepp::detail::fill_message_header_tag) const noexcept
    {
        auto header = operator()(::sbepp::detail::get_header_tag{});
        header.schemaId({1});
        header.templateId({1001});
        header.version({1});
        header.blockLength({24});
        
        
        return header;
    }


    SBEPP_CPP20_CONSTEXPR std::size_t operator()(
        ::sbepp::detail::size_bytes_tag) const noexcept
    {
        const auto last = symbol();
        return ::sbepp::addressof(last) + ::sbepp::size_bytes(last)
               - (*this)(::sbepp::detail::addressof_tag{});
    }


    template<typename Visitor, typename Cursor>
    SBEPP_CPP14_CONSTEXPR void operator()(
        ::sbepp::detail::visit_tag, Visitor& v, Cursor& c)
    {
        v.on_message(*this, c, ::bitget_sbe::schema::messages::Depth50{});
    }


    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_children_tag, Visitor& v, Cursor& c) const
    {
        return v.on_field(this->ts(c), ::bitget_sbe::schema::messages::Depth50::ts{})
||v.on_field(this->seq(c), ::bitget_sbe::schema::messages::Depth50::seq{})
||v.on_field(this->priceExponent(c), ::bitget_sbe::schema::messages::Depth50::priceExponent{})
||v.on_field(this->sizeExponent(c), ::bitget_sbe::schema::messages::Depth50::sizeExponent{})
||v.on_field(this->padding(c), ::bitget_sbe::schema::messages::Depth50::padding{})
||v.on_group(this->asks(c), c, ::bitget_sbe::schema::messages::Depth50::asks{})
||v.on_group(this->bids(c), c, ::bitget_sbe::schema::messages::Depth50::bids{})
||v.on_data(this->symbol(c), ::bitget_sbe::schema::messages::Depth50::symbol{});
    }

};

} // namespace messages
} // namespace bitget_sbe

namespace sbepp
{

template<>
class field_traits<::bitget_sbe::schema::messages::Depth50::ts>
{
public:
    static constexpr const char* name() noexcept
    {
        return "ts";
    }

    static constexpr member_id_t id() noexcept
    {
        return 1;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {0};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::timestampType;
    using value_type_tag = ::bitget_sbe::schema::types::timestampType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::Depth50::seq>
{
public:
    static constexpr const char* name() noexcept
    {
        return "seq";
    }

    static constexpr member_id_t id() noexcept
    {
        return 2;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {8};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::sequenceType;
    using value_type_tag = ::bitget_sbe::schema::types::sequenceType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::Depth50::priceExponent>
{
public:
    static constexpr const char* name() noexcept
    {
        return "priceExponent";
    }

    static constexpr member_id_t id() noexcept
    {
        return 3;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {16};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::exponentType;
    using value_type_tag = ::bitget_sbe::schema::types::exponentType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::Depth50::sizeExponent>
{
public:
    static constexpr const char* name() noexcept
    {
        return "sizeExponent";
    }

    static constexpr member_id_t id() noexcept
    {
        return 4;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {17};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::exponentType;
    using value_type_tag = ::bitget_sbe::schema::types::exponentType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::Depth50::padding>
{
public:
    static constexpr const char* name() noexcept
    {
        return "padding";
    }

    static constexpr member_id_t id() noexcept
    {
        return 100;
    }

    static constexpr const char* description() noexcept
    {
        return "Padding for 8-byte alignment";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {18};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::bitget_sbe::types::padding6<Byte>;
    using value_type_tag = ::bitget_sbe::schema::types::padding6;
};


template<>
class field_traits<::bitget_sbe::schema::messages::Depth50::asks::price>
{
public:
    static constexpr const char* name() noexcept
    {
        return "price";
    }

    static constexpr member_id_t id() noexcept
    {
        return 1;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {0};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::priceType;
    using value_type_tag = ::bitget_sbe::schema::types::priceType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::Depth50::asks::size>
{
public:
    static constexpr const char* name() noexcept
    {
        return "size";
    }

    static constexpr member_id_t id() noexcept
    {
        return 2;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {8};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::sizeType;
    using value_type_tag = ::bitget_sbe::schema::types::sizeType;
};


template<>
class group_traits<::bitget_sbe::schema::messages::Depth50::asks>
{
public:
    static constexpr const char* name() noexcept
    {
        return "asks";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr member_id_t id() noexcept
    {
        return 200;
    }

    static constexpr block_length_t block_length() noexcept
    {
        return 16;
    }

    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::bitget_sbe::detail::messages::asks<Byte>;
    
    template<typename Byte>
    using dimension_type = ::bitget_sbe::types::groupSize16Encoding<Byte>;
    using dimension_type_tag = ::bitget_sbe::schema::types::groupSize16Encoding;
    
    template<typename Byte>
    using entry_type = ::bitget_sbe::detail::messages::asks_entry<Byte>;
    static constexpr ::std::size_t size_bytes(
        const ::std::uint16_t num_in_group) noexcept
    {
        return ::sbepp::composite_traits<dimension_type_tag>::size_bytes()
            + num_in_group * (::sbepp::group_traits<::bitget_sbe::schema::messages::Depth50::asks>::block_length() );
    }

    using field_tags = ::sbepp::type_list<::bitget_sbe::schema::messages::Depth50::asks::price, ::bitget_sbe::schema::messages::Depth50::asks::size>;
    using group_tags = ::sbepp::type_list<>;
    using data_tags = ::sbepp::type_list<>;
};

template<typename Byte>
struct traits_tag<::bitget_sbe::detail::messages::asks<Byte>>
{
    using type = ::bitget_sbe::schema::messages::Depth50::asks;
};

template<typename Byte>
struct traits_tag<::bitget_sbe::detail::messages::asks_entry<Byte>>
{
    using type = ::bitget_sbe::schema::messages::Depth50::asks;
};



template<>
class field_traits<::bitget_sbe::schema::messages::Depth50::bids::price>
{
public:
    static constexpr const char* name() noexcept
    {
        return "price";
    }

    static constexpr member_id_t id() noexcept
    {
        return 1;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {0};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::priceType;
    using value_type_tag = ::bitget_sbe::schema::types::priceType;
};

template<>
class field_traits<::bitget_sbe::schema::messages::Depth50::bids::size>
{
public:
    static constexpr const char* name() noexcept
    {
        return "size";
    }

    static constexpr member_id_t id() noexcept
    {
        return 2;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {8};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bitget_sbe::types::sizeType;
    using value_type_tag = ::bitget_sbe::schema::types::sizeType;
};


template<>
class group_traits<::bitget_sbe::schema::messages::Depth50::bids>
{
public:
    static constexpr const char* name() noexcept
    {
        return "bids";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr member_id_t id() noexcept
    {
        return 201;
    }

    static constexpr block_length_t block_length() noexcept
    {
        return 16;
    }

    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::bitget_sbe::detail::messages::bids<Byte>;
    
    template<typename Byte>
    using dimension_type = ::bitget_sbe::types::groupSize16Encoding<Byte>;
    using dimension_type_tag = ::bitget_sbe::schema::types::groupSize16Encoding;
    
    template<typename Byte>
    using entry_type = ::bitget_sbe::detail::messages::bids_entry<Byte>;
    static constexpr ::std::size_t size_bytes(
        const ::std::uint16_t num_in_group) noexcept
    {
        return ::sbepp::composite_traits<dimension_type_tag>::size_bytes()
            + num_in_group * (::sbepp::group_traits<::bitget_sbe::schema::messages::Depth50::bids>::block_length() );
    }

    using field_tags = ::sbepp::type_list<::bitget_sbe::schema::messages::Depth50::bids::price, ::bitget_sbe::schema::messages::Depth50::bids::size>;
    using group_tags = ::sbepp::type_list<>;
    using data_tags = ::sbepp::type_list<>;
};

template<typename Byte>
struct traits_tag<::bitget_sbe::detail::messages::bids<Byte>>
{
    using type = ::bitget_sbe::schema::messages::Depth50::bids;
};

template<typename Byte>
struct traits_tag<::bitget_sbe::detail::messages::bids_entry<Byte>>
{
    using type = ::bitget_sbe::schema::messages::Depth50::bids;
};


template<>
class data_traits<::bitget_sbe::schema::messages::Depth50::symbol>
{
public:
    static constexpr const char* name() noexcept
    {
        return "symbol";
    }

    static constexpr member_id_t id() noexcept
    {
        return 300;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    template<typename Byte>
    using value_type = ::sbepp::detail::dynamic_array_ref<
    Byte, ::std::uint8_t, ::bitget_sbe::detail::types::length, ::sbepp::endian::little>;

    using length_type = ::bitget_sbe::detail::types::length;
    using length_type_tag = ::bitget_sbe::schema::types::varString8::length;

    static constexpr ::std::size_t size_bytes(
        const length_type::value_type size) noexcept
    {
        return sizeof(size) + size;
    }
};

template<>
class message_traits<::bitget_sbe::schema::messages::Depth50>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Depth50";
    }

    static constexpr const char* description() noexcept
    {
        return "50-level depth snapshot";
    }

    static constexpr message_id_t id() noexcept
    {
        return 1001;
    }

    static constexpr block_length_t block_length() noexcept
    {
        return 24;
    }

    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::bitget_sbe::messages::Depth50<Byte>;
    using schema_tag = ::bitget_sbe::schema;
    static constexpr ::std::size_t size_bytes(
        const ::std::uint16_t asks_num_in_group, 
        const ::std::uint16_t bids_num_in_group, 
        const ::std::size_t total_data_size) noexcept
    {
        return ::sbepp::composite_traits<
            ::sbepp::schema_traits<schema_tag>::header_type_tag>::size_bytes()
            + block_length()
+ ::sbepp::group_traits<::bitget_sbe::schema::messages::Depth50::asks>::size_bytes(asks_num_in_group)
+ ::sbepp::group_traits<::bitget_sbe::schema::messages::Depth50::bids>::size_bytes(bids_num_in_group)
+ ::sbepp::data_traits<::bitget_sbe::schema::messages::Depth50::symbol>::size_bytes(0)
+ total_data_size;
    }

    using field_tags = ::sbepp::type_list<::bitget_sbe::schema::messages::Depth50::ts, ::bitget_sbe::schema::messages::Depth50::seq, ::bitget_sbe::schema::messages::Depth50::priceExponent, ::bitget_sbe::schema::messages::Depth50::sizeExponent, ::bitget_sbe::schema::messages::Depth50::padding>;
    using group_tags = ::sbepp::type_list<::bitget_sbe::schema::messages::Depth50::asks, ::bitget_sbe::schema::messages::Depth50::bids>;
    using data_tags = ::sbepp::type_list<::bitget_sbe::schema::messages::Depth50::symbol>;
};

template<typename Byte>
struct traits_tag<::bitget_sbe::messages::Depth50<Byte>>
{
    using type = ::bitget_sbe::schema::messages::Depth50;
};


} // namespace sbepp

SBEPP_WARNINGS_ON();
