// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Oleksandr Koval

// This file was generated by sbeppc 1.7.0
#pragma once


#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

namespace gate_sbe
{
namespace detail
{
namespace schema
{
namespace types
{
struct Event
{
    struct Subscribe{};
    struct Unsubscribe{};
    struct Update{};
    struct All{};
    struct Api{};

};
struct Role
{
    struct Maker{};
    struct Taker{};

};
struct varString8
{
struct length{};
struct varData{};

};
struct Side
{
    struct SELL{};
    struct BUY{};

};
struct groupSize16Encoding
{
struct blockLength{};
struct numInGroup{};

};
struct PosMarginMode
{
    struct Isolated{};
    struct Cross{};

};
struct blockLength_0{};
struct messageHeader
{
using blockLength = ::gate_sbe::detail::schema::types::blockLength_0;
struct templateId{};
struct schemaId{};
struct version{};

};

} // namespace types
namespace messages
{
struct asks_0
{
    struct pxMantissa{};
    struct szMantissa{};

};
struct bids_0
{
    struct pxMantissa{};
    struct szMantissa{};

};
struct asks_1
{
    struct pxMantissa{};
    struct szMantissa{};

};
struct bids_1
{
    struct pxMantissa{};
    struct szMantissa{};

};
struct trades_0
{
    struct id{};
    struct orderId{};
    struct t{};
    struct sizeMantissa{};
    struct priceMantissa{};
    struct feeMantissa{};
    struct pointFee{};
    struct closeSizeMantissa{};
    struct role : ::gate_sbe::detail::schema::types::Role{};
    struct contract{};
    struct text{};
    struct amendText{};
    struct bizInfo{};

};
struct result_0
{
    struct createTime{};
    struct id{};
    struct sizeExponent{};
    struct icebergMantissa{};
    struct leftMantissa{};
    struct sizeMantissa{};
    struct refu{};
    struct refr{};
    struct finishTime{};
    struct updateId{};
    struct updateTime{};
    struct pointFeeExponent{};
    struct pointFee{};
    struct isClose{};
    struct isLiq{};
    struct isReduceOnly{};
    struct isVoucher{};
    struct pxExponent{};
    struct fillPriceMantissa{};
    struct priceMantissa{};
    struct feeExponent{};
    struct feeMantissa{};
    struct mkfrExponent{};
    struct mkfrMantissa{};
    struct tkfrExponent{};
    struct tkfrMantissa{};
    struct posMarginMode : ::gate_sbe::detail::schema::types::PosMarginMode{};
    struct stopProfitPriceMantissa{};
    struct stopLossPriceMantissa{};
    struct user{};
    struct contract{};
    struct role{};
    struct text{};
    struct tif{};
    struct finishAs{};
    struct status{};
    struct amendText{};
    struct bizInfo{};
    struct stpAct{};
    struct stpId{};
    struct bbo{};
    struct marketOrderSlipRatio{};
    struct leverage{};

};

} // namespace types
} //namespace schema
} // namespace detail
struct schema
{
struct types
{
using Event = ::gate_sbe::detail::schema::types::Event;
using Role = ::gate_sbe::detail::schema::types::Role;
using varString8 = ::gate_sbe::detail::schema::types::varString8;
using Side = ::gate_sbe::detail::schema::types::Side;
using groupSize16Encoding = ::gate_sbe::detail::schema::types::groupSize16Encoding;
using PosMarginMode = ::gate_sbe::detail::schema::types::PosMarginMode;
using messageHeader = ::gate_sbe::detail::schema::types::messageHeader;

};
struct messages
{
struct bbo
{
    struct time{};
    struct e : ::gate_sbe::detail::schema::types::Event{};
    struct t{};
    struct u{};
    struct pxExponent{};
    struct szExponent{};
    struct askMantissaPrice{};
    struct askMantissaSize{};
    struct bidMantissaPrice{};
    struct bidMantissaSize{};
    struct channel{};
    struct s{};

};

struct publicTrade
{
    struct time{};
    struct e : ::gate_sbe::detail::schema::types::Event{};
    struct pxExponent{};
    struct szExponent{};
struct trades
{
    struct t{};
    struct id{};
    struct size{};
    struct price{};

};
    struct channel{};
    struct contract{};

};

struct obu
{
    struct time{};
    struct e : ::gate_sbe::detail::schema::types::Event{};
    struct t{};
    struct full{};
    struct firstID{};
    struct lastID{};
    struct pxExponent{};
    struct szExponent{};
struct bids
{
    struct pxMantissa{};
    struct szMantissa{};

};
struct asks
{
    struct pxMantissa{};
    struct szMantissa{};

};
    struct channel{};
    struct symbol{};

};

struct orderBook
{
    struct time{};
    struct e : ::gate_sbe::detail::schema::types::Event{};
    struct t{};
    struct id{};
    struct pxExponent{};
    struct szExponent{};
    struct level{};
    using asks = ::gate_sbe::detail::schema::messages::asks_0;
    using bids = ::gate_sbe::detail::schema::messages::bids_0;
    struct channel{};
    struct contract{};

};

struct orderBookUpdate
{
    struct time{};
    struct e : ::gate_sbe::detail::schema::types::Event{};
    struct t{};
    struct firstID{};
    struct lastID{};
    struct pxExponent{};
    struct szExponent{};
    struct level{};
    using asks = ::gate_sbe::detail::schema::messages::asks_1;
    using bids = ::gate_sbe::detail::schema::messages::bids_1;
    struct channel{};
    struct symbol{};

};

struct userTrade
{
    struct time{};
    struct e : ::gate_sbe::detail::schema::types::Event{};
    struct pxExponent{};
    struct szExponent{};
    struct feeExponent{};
    struct pointExponent{};
    using trades = ::gate_sbe::detail::schema::messages::trades_0;
    struct channel{};

};

struct position
{
    struct time{};
    struct e : ::gate_sbe::detail::schema::types::Event{};
    struct t{};
    struct updateId{};
    struct crossLeverageLimit{};
    struct riskLimit{};
    struct leverage{};
    struct historyPoint{};
    struct margin{};
    struct realisedPoint{};
    struct lever{};
    struct user{};
    struct pxExponent{};
    struct liqPriceMantissa{};
    struct entryPriceMantissa{};
    struct leverageMaxExponent{};
    struct leverageMaxMantissa{};
    struct maintenanceRateExponent{};
    struct maintenanceRateMantissa{};
    struct szExponent{};
    struct size{};
    struct lastClosePnlExponent{};
    struct lastClosePnlMantissa{};
    struct realisedPnlExponent{};
    struct realisedPnlMantissa{};
    struct historyPnlExponent{};
    struct historyPnlMantissa{};
    struct crossLeverageLimitExponent{};
    struct riskLimitExponent{};
    struct leverageExponent{};
    struct historyPointExponent{};
    struct marginExponent{};
    struct realisedPointExponent{};
    struct channel{};
    struct contract{};
    struct mode{};
    struct posMarginMode{};
    struct leverStr{};

};

struct candlestick
{
    struct time{};
    struct e : ::gate_sbe::detail::schema::types::Event{};
    struct pxExponent{};
    struct szExponent{};
    struct amountExponent{};
struct candlesticks
{
    struct t{};
    struct openMantissa{};
    struct highMantissa{};
    struct lowMantissa{};
    struct closeMantissa{};
    struct volumeMantissa{};
    struct amountMantissa{};
    struct complete{};
    struct name{};

};
    struct channel{};

};

struct futuresTicker
{
    struct time{};
    struct e : ::gate_sbe::detail::schema::types::Event{};
struct result
{
    struct t{};
    struct pxExponent{};
    struct lastMantissa{};
    struct changePriceMantissa{};
    struct low24hMantissa{};
    struct high24hMantissa{};
    struct markPxExponent{};
    struct markPriceMantissa{};
    struct indexPxExponent{};
    struct indexPriceMantissa{};
    struct changePercentageExponent{};
    struct changePercentageMantissa{};
    struct fundingRateExponent{};
    struct fundingRateMantissa{};
    struct szExponent{};
    struct totalSize{};
    struct volume24hExponent{};
    struct volume24hMantissa{};
    struct volume24hBaseExponent{};
    struct volume24hBaseMantissa{};
    struct volume24hQuoteExponent{};
    struct volume24hQuoteMantissa{};
    struct volume24hSettleExponent{};
    struct volume24hSettleMantissa{};
    struct contract{};
    struct quantoBaseRate{};
    struct priceType{};
    struct changeFrom{};

};
    struct channel{};

};

struct orders
{
    struct time{};
    struct e : ::gate_sbe::detail::schema::types::Event{};
    using result = ::gate_sbe::detail::schema::messages::result_0;
    struct channel{};

};


};
};


namespace types
{
template<typename Byte>
class messageHeader;
} // namespace types
} // namespace gate_sbe

namespace sbepp
{

template<>
class schema_traits<::gate_sbe::schema>
{
public:
    static constexpr const char* package() noexcept
    {
        return "gate_fex_ws_sbe";
    }

    static constexpr schema_id_t id() noexcept
    {
        return 1;
    }

    static constexpr version_t version() noexcept
    {
        return 1;
    }

    static constexpr const char* semantic_version() noexcept
    {
        return "1.0.0";
    }

    static constexpr endian byte_order() noexcept
    {
        return ::sbepp::endian::little;
    }

    static constexpr const char* description() noexcept
    {
        return "Gate FEX SBE Schema for WebSocket Market Data";
    }

    
    template<typename Byte>
    using header_type = ::gate_sbe::types::messageHeader<Byte>;
    using header_type_tag = ::gate_sbe::schema::types::messageHeader;
    using type_tags = ::sbepp::type_list<::gate_sbe::schema::types::Event, ::gate_sbe::schema::types::Role, ::gate_sbe::schema::types::varString8, ::gate_sbe::schema::types::Side, ::gate_sbe::schema::types::groupSize16Encoding, ::gate_sbe::schema::types::PosMarginMode, ::gate_sbe::schema::types::messageHeader>;
    using message_tags = ::sbepp::type_list<::gate_sbe::schema::messages::bbo, ::gate_sbe::schema::messages::publicTrade, ::gate_sbe::schema::messages::obu, ::gate_sbe::schema::messages::orderBook, ::gate_sbe::schema::messages::orderBookUpdate, ::gate_sbe::schema::messages::userTrade, ::gate_sbe::schema::messages::position, ::gate_sbe::schema::messages::candlestick, ::gate_sbe::schema::messages::futuresTicker, ::gate_sbe::schema::messages::orders>;
};

} // namespace sbepp

SBEPP_WARNINGS_ON();
